name: Chess Game

on:
  issues:
    types: [opened]

jobs:
  process-move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install python-chess cairosvg discord-webhook

      - name: Run the chess move script
        run: |
          python3 readme_chess.py "${{ github.event.issue.title }}"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated board after move"
          git push

