name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@v2.0.0
        id: snake-gif
        with:
          github_user_name: Brunosilva-data # Seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: '#0033A0' # Cor azul da cobra

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


  
